/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.ApprovalFlowRouteResponseApprovalFlowRouteSteps;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApprovalFlowRouteResponseApprovalFlowRoute
 */
public class ApprovalFlowRouteResponseApprovalFlowRouteTest {
    private final ApprovalFlowRouteResponseApprovalFlowRoute model = new ApprovalFlowRouteResponseApprovalFlowRoute();

    /**
     * Model tests for ApprovalFlowRouteResponseApprovalFlowRoute
     */
    @Test
    public void testApprovalFlowRouteResponseApprovalFlowRoute() {
        // TODO: test ApprovalFlowRouteResponseApprovalFlowRoute
    }

    /**
     * Test the property 'definitionSystem'
     */
    @Test
    public void definitionSystemTest() {
        // TODO: test definitionSystem
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'firstStepId'
     */
    @Test
    public void firstStepIdTest() {
        // TODO: test firstStepId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'requestFormIds'
     */
    @Test
    public void requestFormIdsTest() {
        // TODO: test requestFormIds
    }

    /**
     * Test the property 'steps'
     */
    @Test
    public void stepsTest() {
        // TODO: test steps
    }

    /**
     * Test the property 'usages'
     */
    @Test
    public void usagesTest() {
        // TODO: test usages
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
