/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApprovalRequestResponseApprovalRequestComments
 */
public class ApprovalRequestResponseApprovalRequestCommentsTest {
    private final ApprovalRequestResponseApprovalRequestComments model = new ApprovalRequestResponseApprovalRequestComments();

    /**
     * Model tests for ApprovalRequestResponseApprovalRequestComments
     */
    @Test
    public void testApprovalRequestResponseApprovalRequestComments() {
        // TODO: test ApprovalRequestResponseApprovalRequestComments
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'postedAt'
     */
    @Test
    public void postedAtTest() {
        // TODO: test postedAt
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
