/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.CompanyResponseCompanyAccountItems;
import jp.co.freee.accounting.models.CompanyResponseCompanyItems;
import jp.co.freee.accounting.models.CompanyResponseCompanyPartners;
import jp.co.freee.accounting.models.CompanyResponseCompanySections;
import jp.co.freee.accounting.models.CompanyResponseCompanyTags;
import jp.co.freee.accounting.models.CompanyResponseCompanyTaxCodes;
import jp.co.freee.accounting.models.CompanyResponseCompanyTaxes;
import jp.co.freee.accounting.models.CompanyResponseCompanyWalletables;
import jp.co.freee.accounting.models.FiscalYears;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CompanyResponseCompany
 */
public class CompanyResponseCompanyTest {
    private final CompanyResponseCompany model = new CompanyResponseCompany();

    /**
     * Model tests for CompanyResponseCompany
     */
    @Test
    public void testCompanyResponseCompany() {
        // TODO: test CompanyResponseCompany
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'accountItems'
     */
    @Test
    public void accountItemsTest() {
        // TODO: test accountItems
    }

    /**
     * Test the property 'amountFraction'
     */
    @Test
    public void amountFractionTest() {
        // TODO: test amountFraction
    }

    /**
     * Test the property 'contactName'
     */
    @Test
    public void contactNameTest() {
        // TODO: test contactName
    }

    /**
     * Test the property 'corporateNumber'
     */
    @Test
    public void corporateNumberTest() {
        // TODO: test corporateNumber
    }

    /**
     * Test the property 'defaultWalletAccountId'
     */
    @Test
    public void defaultWalletAccountIdTest() {
        // TODO: test defaultWalletAccountId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'fax'
     */
    @Test
    public void faxTest() {
        // TODO: test fax
    }

    /**
     * Test the property 'fiscalYears'
     */
    @Test
    public void fiscalYearsTest() {
        // TODO: test fiscalYears
    }

    /**
     * Test the property 'headCount'
     */
    @Test
    public void headCountTest() {
        // TODO: test headCount
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'industryClass'
     */
    @Test
    public void industryClassTest() {
        // TODO: test industryClass
    }

    /**
     * Test the property 'industryCode'
     */
    @Test
    public void industryCodeTest() {
        // TODO: test industryCode
    }

    /**
     * Test the property 'invoiceLayout'
     */
    @Test
    public void invoiceLayoutTest() {
        // TODO: test invoiceLayout
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'minusFormat'
     */
    @Test
    public void minusFormatTest() {
        // TODO: test minusFormat
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nameKana'
     */
    @Test
    public void nameKanaTest() {
        // TODO: test nameKana
    }

    /**
     * Test the property 'partners'
     */
    @Test
    public void partnersTest() {
        // TODO: test partners
    }

    /**
     * Test the property 'phone1'
     */
    @Test
    public void phone1Test() {
        // TODO: test phone1
    }

    /**
     * Test the property 'phone2'
     */
    @Test
    public void phone2Test() {
        // TODO: test phone2
    }

    /**
     * Test the property 'prefectureCode'
     */
    @Test
    public void prefectureCodeTest() {
        // TODO: test prefectureCode
    }

    /**
     * Test the property 'privateSettlement'
     */
    @Test
    public void privateSettlementTest() {
        // TODO: test privateSettlement
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'sections'
     */
    @Test
    public void sectionsTest() {
        // TODO: test sections
    }

    /**
     * Test the property 'streetName1'
     */
    @Test
    public void streetName1Test() {
        // TODO: test streetName1
    }

    /**
     * Test the property 'streetName2'
     */
    @Test
    public void streetName2Test() {
        // TODO: test streetName2
    }

    /**
     * Test the property 'taxAtSourceCalcType'
     */
    @Test
    public void taxAtSourceCalcTypeTest() {
        // TODO: test taxAtSourceCalcType
    }

    /**
     * Test the property 'taxCodes'
     */
    @Test
    public void taxCodesTest() {
        // TODO: test taxCodes
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

    /**
     * Test the property 'txnNumberFormat'
     */
    @Test
    public void txnNumberFormatTest() {
        // TODO: test txnNumberFormat
    }

    /**
     * Test the property 'usePartnerCode'
     */
    @Test
    public void usePartnerCodeTest() {
        // TODO: test usePartnerCode
    }

    /**
     * Test the property 'walletables'
     */
    @Test
    public void walletablesTest() {
        // TODO: test walletables
    }

    /**
     * Test the property 'workflowSetting'
     */
    @Test
    public void workflowSettingTest() {
        // TODO: test workflowSetting
    }

    /**
     * Test the property 'zipcode'
     */
    @Test
    public void zipcodeTest() {
        // TODO: test zipcode
    }

}
