/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExpenseApplicationLineTemplateParams
 */
public class ExpenseApplicationLineTemplateParamsTest {
    private final ExpenseApplicationLineTemplateParams model = new ExpenseApplicationLineTemplateParams();

    /**
     * Model tests for ExpenseApplicationLineTemplateParams
     */
    @Test
    public void testExpenseApplicationLineTemplateParams() {
        // TODO: test ExpenseApplicationLineTemplateParams
    }

    /**
     * Test the property 'accountItemId'
     */
    @Test
    public void accountItemIdTest() {
        // TODO: test accountItemId
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    public void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'lineDescription'
     */
    @Test
    public void lineDescriptionTest() {
        // TODO: test lineDescription
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'requiredReceipt'
     */
    @Test
    public void requiredReceiptTest() {
        // TODO: test requiredReceipt
    }

    /**
     * Test the property 'taxCode'
     */
    @Test
    public void taxCodeTest() {
        // TODO: test taxCode
    }

}
