/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.ExpenseApplicationUpdateParamsExpenseApplicationLines1;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExpenseApplicationUpdateParamsPurchaseLines
 */
public class ExpenseApplicationUpdateParamsPurchaseLinesTest {
    private final ExpenseApplicationUpdateParamsPurchaseLines model = new ExpenseApplicationUpdateParamsPurchaseLines();

    /**
     * Model tests for ExpenseApplicationUpdateParamsPurchaseLines
     */
    @Test
    public void testExpenseApplicationUpdateParamsPurchaseLines() {
        // TODO: test ExpenseApplicationUpdateParamsPurchaseLines
    }

    /**
     * Test the property 'expenseApplicationLines'
     */
    @Test
    public void expenseApplicationLinesTest() {
        // TODO: test expenseApplicationLines
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'receiptId'
     */
    @Test
    public void receiptIdTest() {
        // TODO: test receiptId
    }

    /**
     * Test the property 'transactionDate'
     */
    @Test
    public void transactionDateTest() {
        // TODO: test transactionDate
    }

}
