/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.ExpenseApplicationCreateParamsExpenseApplicationLines;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExpenseApplicationCreateParams
 */
public class ExpenseApplicationCreateParamsTest {
    private final ExpenseApplicationCreateParams model = new ExpenseApplicationCreateParams();

    /**
     * Model tests for ExpenseApplicationCreateParams
     */
    @Test
    public void testExpenseApplicationCreateParams() {
        // TODO: test ExpenseApplicationCreateParams
    }

    /**
     * Test the property 'approvalFlowRouteId'
     */
    @Test
    public void approvalFlowRouteIdTest() {
        // TODO: test approvalFlowRouteId
    }

    /**
     * Test the property 'approverId'
     */
    @Test
    public void approverIdTest() {
        // TODO: test approverId
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'draft'
     */
    @Test
    public void draftTest() {
        // TODO: test draft
    }

    /**
     * Test the property 'expenseApplicationLines'
     */
    @Test
    public void expenseApplicationLinesTest() {
        // TODO: test expenseApplicationLines
    }

    /**
     * Test the property 'issueDate'
     */
    @Test
    public void issueDateTest() {
        // TODO: test issueDate
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'sectionId'
     */
    @Test
    public void sectionIdTest() {
        // TODO: test sectionId
    }

    /**
     * Test the property 'segment1TagId'
     */
    @Test
    public void segment1TagIdTest() {
        // TODO: test segment1TagId
    }

    /**
     * Test the property 'segment2TagId'
     */
    @Test
    public void segment2TagIdTest() {
        // TODO: test segment2TagId
    }

    /**
     * Test the property 'segment3TagId'
     */
    @Test
    public void segment3TagIdTest() {
        // TODO: test segment3TagId
    }

    /**
     * Test the property 'tagIds'
     */
    @Test
    public void tagIdsTest() {
        // TODO: test tagIds
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
