/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FixedAsset
 */
public class FixedAssetTest {
    private final FixedAsset model = new FixedAsset();

    /**
     * Model tests for FixedAsset
     */
    @Test
    public void testFixedAsset() {
        // TODO: test FixedAsset
    }

    /**
     * Test the property 'accountItemId'
     */
    @Test
    public void accountItemIdTest() {
        // TODO: test accountItemId
    }

    /**
     * Test the property 'acquisitionCost'
     */
    @Test
    public void acquisitionCostTest() {
        // TODO: test acquisitionCost
    }

    /**
     * Test the property 'acquisitionDate'
     */
    @Test
    public void acquisitionDateTest() {
        // TODO: test acquisitionDate
    }

    /**
     * Test the property 'cityName'
     */
    @Test
    public void cityNameTest() {
        // TODO: test cityName
    }

    /**
     * Test the property 'closingAccumulatedDepreciation'
     */
    @Test
    public void closingAccumulatedDepreciationTest() {
        // TODO: test closingAccumulatedDepreciation
    }

    /**
     * Test the property 'closingBalance'
     */
    @Test
    public void closingBalanceTest() {
        // TODO: test closingBalance
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'depreciationAccountItemId'
     */
    @Test
    public void depreciationAccountItemIdTest() {
        // TODO: test depreciationAccountItemId
    }

    /**
     * Test the property 'depreciationAmount'
     */
    @Test
    public void depreciationAmountTest() {
        // TODO: test depreciationAmount
    }

    /**
     * Test the property 'depreciationMethod'
     */
    @Test
    public void depreciationMethodTest() {
        // TODO: test depreciationMethod
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    public void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'lifeYears'
     */
    @Test
    public void lifeYearsTest() {
        // TODO: test lifeYears
    }

    /**
     * Test the property 'managementNumber'
     */
    @Test
    public void managementNumberTest() {
        // TODO: test managementNumber
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'openingAccumulatedDepreciation'
     */
    @Test
    public void openingAccumulatedDepreciationTest() {
        // TODO: test openingAccumulatedDepreciation
    }

    /**
     * Test the property 'openingBalance'
     */
    @Test
    public void openingBalanceTest() {
        // TODO: test openingBalance
    }

    /**
     * Test the property 'prefectureCode'
     */
    @Test
    public void prefectureCodeTest() {
        // TODO: test prefectureCode
    }

    /**
     * Test the property 'retireDate'
     */
    @Test
    public void retireDateTest() {
        // TODO: test retireDate
    }

    /**
     * Test the property 'retireType'
     */
    @Test
    public void retireTypeTest() {
        // TODO: test retireType
    }

    /**
     * Test the property 'sectionId'
     */
    @Test
    public void sectionIdTest() {
        // TODO: test sectionId
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
