/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.WalletTxn;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse20014
 */
public class InlineResponse20014Test {
    private final InlineResponse20014 model = new InlineResponse20014();

    /**
     * Model tests for InlineResponse20014
     */
    @Test
    public void testInlineResponse20014() {
        // TODO: test InlineResponse20014
    }

    /**
     * Test the property 'walletTxns'
     */
    @Test
    public void walletTxnsTest() {
        // TODO: test walletTxns
    }

}
