/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import jp.co.freee.accounting.models.JournalsResponseJournals;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JournalsResponse
 */
public class JournalsResponseTest {
    private final JournalsResponse model = new JournalsResponse();

    /**
     * Model tests for JournalsResponse
     */
    @Test
    public void testJournalsResponse() {
        // TODO: test JournalsResponse
    }

    /**
     * Test the property 'journals'
     */
    @Test
    public void journalsTest() {
        // TODO: test journals
    }

}
