/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.InvoiceIndexResponseTotalAmountPerVatRate;
import jp.co.freee.accounting.models.QuotationIndexResponseQuotationContents;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for QuotationIndexResponseQuotations
 */
public class QuotationIndexResponseQuotationsTest {
    private final QuotationIndexResponseQuotations model = new QuotationIndexResponseQuotations();

    /**
     * Model tests for QuotationIndexResponseQuotations
     */
    @Test
    public void testQuotationIndexResponseQuotations() {
        // TODO: test QuotationIndexResponseQuotations
    }

    /**
     * Test the property 'companyAddress1'
     */
    @Test
    public void companyAddress1Test() {
        // TODO: test companyAddress1
    }

    /**
     * Test the property 'companyAddress2'
     */
    @Test
    public void companyAddress2Test() {
        // TODO: test companyAddress2
    }

    /**
     * Test the property 'companyContactInfo'
     */
    @Test
    public void companyContactInfoTest() {
        // TODO: test companyContactInfo
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'companyPrefectureCode'
     */
    @Test
    public void companyPrefectureCodeTest() {
        // TODO: test companyPrefectureCode
    }

    /**
     * Test the property 'companyPrefectureName'
     */
    @Test
    public void companyPrefectureNameTest() {
        // TODO: test companyPrefectureName
    }

    /**
     * Test the property 'companyZipcode'
     */
    @Test
    public void companyZipcodeTest() {
        // TODO: test companyZipcode
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'issueDate'
     */
    @Test
    public void issueDateTest() {
        // TODO: test issueDate
    }

    /**
     * Test the property 'mailSentAt'
     */
    @Test
    public void mailSentAtTest() {
        // TODO: test mailSentAt
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'partnerAddress1'
     */
    @Test
    public void partnerAddress1Test() {
        // TODO: test partnerAddress1
    }

    /**
     * Test the property 'partnerAddress2'
     */
    @Test
    public void partnerAddress2Test() {
        // TODO: test partnerAddress2
    }

    /**
     * Test the property 'partnerCode'
     */
    @Test
    public void partnerCodeTest() {
        // TODO: test partnerCode
    }

    /**
     * Test the property 'partnerContactInfo'
     */
    @Test
    public void partnerContactInfoTest() {
        // TODO: test partnerContactInfo
    }

    /**
     * Test the property 'partnerDisplayName'
     */
    @Test
    public void partnerDisplayNameTest() {
        // TODO: test partnerDisplayName
    }

    /**
     * Test the property 'partnerId'
     */
    @Test
    public void partnerIdTest() {
        // TODO: test partnerId
    }

    /**
     * Test the property 'partnerName'
     */
    @Test
    public void partnerNameTest() {
        // TODO: test partnerName
    }

    /**
     * Test the property 'partnerPrefectureCode'
     */
    @Test
    public void partnerPrefectureCodeTest() {
        // TODO: test partnerPrefectureCode
    }

    /**
     * Test the property 'partnerPrefectureName'
     */
    @Test
    public void partnerPrefectureNameTest() {
        // TODO: test partnerPrefectureName
    }

    /**
     * Test the property 'partnerTitle'
     */
    @Test
    public void partnerTitleTest() {
        // TODO: test partnerTitle
    }

    /**
     * Test the property 'partnerZipcode'
     */
    @Test
    public void partnerZipcodeTest() {
        // TODO: test partnerZipcode
    }

    /**
     * Test the property 'quotationContents'
     */
    @Test
    public void quotationContentsTest() {
        // TODO: test quotationContents
    }

    /**
     * Test the property 'quotationLayout'
     */
    @Test
    public void quotationLayoutTest() {
        // TODO: test quotationLayout
    }

    /**
     * Test the property 'quotationNumber'
     */
    @Test
    public void quotationNumberTest() {
        // TODO: test quotationNumber
    }

    /**
     * Test the property 'quotationStatus'
     */
    @Test
    public void quotationStatusTest() {
        // TODO: test quotationStatus
    }

    /**
     * Test the property 'subTotal'
     */
    @Test
    public void subTotalTest() {
        // TODO: test subTotal
    }

    /**
     * Test the property 'taxEntryMethod'
     */
    @Test
    public void taxEntryMethodTest() {
        // TODO: test taxEntryMethod
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'totalAmount'
     */
    @Test
    public void totalAmountTest() {
        // TODO: test totalAmount
    }

    /**
     * Test the property 'totalAmountPerVatRate'
     */
    @Test
    public void totalAmountPerVatRateTest() {
        // TODO: test totalAmountPerVatRate
    }

    /**
     * Test the property 'totalVat'
     */
    @Test
    public void totalVatTest() {
        // TODO: test totalVat
    }

    /**
     * Test the property 'webConfirmedAt'
     */
    @Test
    public void webConfirmedAtTest() {
        // TODO: test webConfirmedAt
    }

    /**
     * Test the property 'webDownloadedAt'
     */
    @Test
    public void webDownloadedAtTest() {
        // TODO: test webDownloadedAt
    }

    /**
     * Test the property 'webPublishedAt'
     */
    @Test
    public void webPublishedAtTest() {
        // TODO: test webPublishedAt
    }

}
