/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.SelectablesIndexResponseAccountItems;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SelectablesIndexResponseAccountCategories
 */
public class SelectablesIndexResponseAccountCategoriesTest {
    private final SelectablesIndexResponseAccountCategories model = new SelectablesIndexResponseAccountCategories();

    /**
     * Model tests for SelectablesIndexResponseAccountCategories
     */
    @Test
    public void testSelectablesIndexResponseAccountCategories() {
        // TODO: test SelectablesIndexResponseAccountCategories
    }

    /**
     * Test the property 'accountItems'
     */
    @Test
    public void accountItemsTest() {
        // TODO: test accountItems
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'desc'
     */
    @Test
    public void descTest() {
        // TODO: test desc
    }

    /**
     * Test the property 'orgCode'
     */
    @Test
    public void orgCodeTest() {
        // TODO: test orgCode
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
