/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TrialCrTwoYearsResponseTrialCrTwoYearsPartners
 */
public class TrialCrTwoYearsResponseTrialCrTwoYearsPartnersTest {
    private final TrialCrTwoYearsResponseTrialCrTwoYearsPartners model = new TrialCrTwoYearsResponseTrialCrTwoYearsPartners();

    /**
     * Model tests for TrialCrTwoYearsResponseTrialCrTwoYearsPartners
     */
    @Test
    public void testTrialCrTwoYearsResponseTrialCrTwoYearsPartners() {
        // TODO: test TrialCrTwoYearsResponseTrialCrTwoYearsPartners
    }

    /**
     * Test the property 'closingBalance'
     */
    @Test
    public void closingBalanceTest() {
        // TODO: test closingBalance
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastYearClosingBalance'
     */
    @Test
    public void lastYearClosingBalanceTest() {
        // TODO: test lastYearClosingBalance
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'yearOnYear'
     */
    @Test
    public void yearOnYearTest() {
        // TODO: test yearOnYear
    }

}
