/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.TrialCrSegment1TagsResponseTrialCrSegment1TagsSegment1Tags;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TrialCrSegment1TagsResponseTrialCrSegment1TagsBalances
 */
public class TrialCrSegment1TagsResponseTrialCrSegment1TagsBalancesTest {
    private final TrialCrSegment1TagsResponseTrialCrSegment1TagsBalances model = new TrialCrSegment1TagsResponseTrialCrSegment1TagsBalances();

    /**
     * Model tests for TrialCrSegment1TagsResponseTrialCrSegment1TagsBalances
     */
    @Test
    public void testTrialCrSegment1TagsResponseTrialCrSegment1TagsBalances() {
        // TODO: test TrialCrSegment1TagsResponseTrialCrSegment1TagsBalances
    }

    /**
     * Test the property 'accountCategoryName'
     */
    @Test
    public void accountCategoryNameTest() {
        // TODO: test accountCategoryName
    }

    /**
     * Test the property 'accountGroupName'
     */
    @Test
    public void accountGroupNameTest() {
        // TODO: test accountGroupName
    }

    /**
     * Test the property 'accountItemId'
     */
    @Test
    public void accountItemIdTest() {
        // TODO: test accountItemId
    }

    /**
     * Test the property 'accountItemName'
     */
    @Test
    public void accountItemNameTest() {
        // TODO: test accountItemName
    }

    /**
     * Test the property 'closingBalance'
     */
    @Test
    public void closingBalanceTest() {
        // TODO: test closingBalance
    }

    /**
     * Test the property 'hierarchyLevel'
     */
    @Test
    public void hierarchyLevelTest() {
        // TODO: test hierarchyLevel
    }

    /**
     * Test the property 'parentAccountCategoryName'
     */
    @Test
    public void parentAccountCategoryNameTest() {
        // TODO: test parentAccountCategoryName
    }

    /**
     * Test the property 'segment1Tags'
     */
    @Test
    public void segment1TagsTest() {
        // TODO: test segment1Tags
    }

    /**
     * Test the property 'totalLine'
     */
    @Test
    public void totalLineTest() {
        // TODO: test totalLine
    }

}
