/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.JournalsResponseJournalsUpToDateReasons;
import jp.co.freee.accounting.models.TrialCrSegment1TagsResponseTrialCrSegment1Tags;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TrialCrSegment1TagsResponse
 */
public class TrialCrSegment1TagsResponseTest {
    private final TrialCrSegment1TagsResponse model = new TrialCrSegment1TagsResponse();

    /**
     * Model tests for TrialCrSegment1TagsResponse
     */
    @Test
    public void testTrialCrSegment1TagsResponse() {
        // TODO: test TrialCrSegment1TagsResponse
    }

    /**
     * Test the property 'trialCrSegment1Tags'
     */
    @Test
    public void trialCrSegment1TagsTest() {
        // TODO: test trialCrSegment1Tags
    }

    /**
     * Test the property 'upToDate'
     */
    @Test
    public void upToDateTest() {
        // TODO: test upToDate
    }

    /**
     * Test the property 'upToDateReasons'
     */
    @Test
    public void upToDateReasonsTest() {
        // TODO: test upToDateReasons
    }

}
