/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import jp.co.freee.accounting.models.ApprovalRequestFormResponseApprovalRequestForm;

/**
 * ApprovalRequestFormResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApprovalRequestFormResponse {
  public static final String SERIALIZED_NAME_APPROVAL_REQUEST_FORM = "approval_request_form";
  @SerializedName(SERIALIZED_NAME_APPROVAL_REQUEST_FORM)
  private ApprovalRequestFormResponseApprovalRequestForm approvalRequestForm;

  public ApprovalRequestFormResponse() { 
  }

  public ApprovalRequestFormResponse approvalRequestForm(ApprovalRequestFormResponseApprovalRequestForm approvalRequestForm) {
    
    this.approvalRequestForm = approvalRequestForm;
    return this;
  }

   /**
   * Get approvalRequestForm
   * @return approvalRequestForm
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ApprovalRequestFormResponseApprovalRequestForm getApprovalRequestForm() {
    return approvalRequestForm;
  }


  public void setApprovalRequestForm(ApprovalRequestFormResponseApprovalRequestForm approvalRequestForm) {
    this.approvalRequestForm = approvalRequestForm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApprovalRequestFormResponse approvalRequestFormResponse = (ApprovalRequestFormResponse) o;
    return Objects.equals(this.approvalRequestForm, approvalRequestFormResponse.approvalRequestForm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approvalRequestForm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApprovalRequestFormResponse {\n");
    sb.append("    approvalRequestForm: ").append(toIndentedString(approvalRequestForm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

