/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.QuotationIndexResponseQuotations;

/**
 * QuotationIndexResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class QuotationIndexResponse {
  public static final String SERIALIZED_NAME_QUOTATIONS = "quotations";
  @SerializedName(SERIALIZED_NAME_QUOTATIONS)
  private List<QuotationIndexResponseQuotations> quotations = new ArrayList<>();

  public QuotationIndexResponse() { 
  }

  public QuotationIndexResponse quotations(List<QuotationIndexResponseQuotations> quotations) {
    
    this.quotations = quotations;
    return this;
  }

  public QuotationIndexResponse addQuotationsItem(QuotationIndexResponseQuotations quotationsItem) {
    this.quotations.add(quotationsItem);
    return this;
  }

   /**
   * Get quotations
   * @return quotations
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<QuotationIndexResponseQuotations> getQuotations() {
    return quotations;
  }


  public void setQuotations(List<QuotationIndexResponseQuotations> quotations) {
    this.quotations = quotations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotationIndexResponse quotationIndexResponse = (QuotationIndexResponse) o;
    return Objects.equals(this.quotations, quotationIndexResponse.quotations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quotations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotationIndexResponse {\n");
    sb.append("    quotations: ").append(toIndentedString(quotations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

