/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SelectablesIndexResponseAccountGroups
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SelectablesIndexResponseAccountGroups {
  public static final String SERIALIZED_NAME_ACCOUNT_CATEGORY_ID = "account_category_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_CATEGORY_ID)
  private Integer accountCategoryId;

  public static final String SERIALIZED_NAME_ACCOUNT_STRUCTURE_ID = "account_structure_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_STRUCTURE_ID)
  private Integer accountStructureId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_DETAIL_TYPE = "detail_type";
  @SerializedName(SERIALIZED_NAME_DETAIL_TYPE)
  private Integer detailType;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public SelectablesIndexResponseAccountGroups() { 
  }

  public SelectablesIndexResponseAccountGroups accountCategoryId(Integer accountCategoryId) {
    
    this.accountCategoryId = accountCategoryId;
    return this;
  }

   /**
   * 勘定科目カテゴリーID
   * minimum: 1
   * maximum: 2147483647
   * @return accountCategoryId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "勘定科目カテゴリーID")

  public Integer getAccountCategoryId() {
    return accountCategoryId;
  }


  public void setAccountCategoryId(Integer accountCategoryId) {
    this.accountCategoryId = accountCategoryId;
  }


  public SelectablesIndexResponseAccountGroups accountStructureId(Integer accountStructureId) {
    
    this.accountStructureId = accountStructureId;
    return this;
  }

   /**
   * 年度ID
   * minimum: 1
   * maximum: 2147483647
   * @return accountStructureId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "年度ID")

  public Integer getAccountStructureId() {
    return accountStructureId;
  }


  public void setAccountStructureId(Integer accountStructureId) {
    this.accountStructureId = accountStructureId;
  }


  public SelectablesIndexResponseAccountGroups createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 作成日時
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-12-17T13:47:24+09:00", value = "作成日時")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public SelectablesIndexResponseAccountGroups detailType(Integer detailType) {
    
    this.detailType = detailType;
    return this;
  }

   /**
   * 詳細パラメータの種類
   * minimum: 0
   * maximum: 4
   * @return detailType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "詳細パラメータの種類")

  public Integer getDetailType() {
    return detailType;
  }


  public void setDetailType(Integer detailType) {
    this.detailType = detailType;
  }


  public SelectablesIndexResponseAccountGroups id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * 決算書表示名（小カテゴリー）ID
   * minimum: 1
   * maximum: 2147483647
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "決算書表示名（小カテゴリー）ID")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public SelectablesIndexResponseAccountGroups index(Integer index) {
    
    this.index = index;
    return this;
  }

   /**
   * 並び順
   * @return index
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "並び順")

  public Integer getIndex() {
    return index;
  }


  public void setIndex(Integer index) {
    this.index = index;
  }


  public SelectablesIndexResponseAccountGroups name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * 決算書表示名
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "預託金", required = true, value = "決算書表示名")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SelectablesIndexResponseAccountGroups updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 更新日時
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-12-17T13:47:24+09:00", value = "更新日時")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectablesIndexResponseAccountGroups selectablesIndexResponseAccountGroups = (SelectablesIndexResponseAccountGroups) o;
    return Objects.equals(this.accountCategoryId, selectablesIndexResponseAccountGroups.accountCategoryId) &&
        Objects.equals(this.accountStructureId, selectablesIndexResponseAccountGroups.accountStructureId) &&
        Objects.equals(this.createdAt, selectablesIndexResponseAccountGroups.createdAt) &&
        Objects.equals(this.detailType, selectablesIndexResponseAccountGroups.detailType) &&
        Objects.equals(this.id, selectablesIndexResponseAccountGroups.id) &&
        Objects.equals(this.index, selectablesIndexResponseAccountGroups.index) &&
        Objects.equals(this.name, selectablesIndexResponseAccountGroups.name) &&
        Objects.equals(this.updatedAt, selectablesIndexResponseAccountGroups.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountCategoryId, accountStructureId, createdAt, detailType, id, index, name, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectablesIndexResponseAccountGroups {\n");
    sb.append("    accountCategoryId: ").append(toIndentedString(accountCategoryId)).append("\n");
    sb.append("    accountStructureId: ").append(toIndentedString(accountStructureId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    detailType: ").append(toIndentedString(detailType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

