/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import jp.co.freee.accounting.models.SelectablesIndexResponseDefaultTaxTaxRate5;
import jp.co.freee.accounting.models.SelectablesIndexResponseDefaultTaxTaxRate8;

/**
 * SelectablesIndexResponseDefaultTax
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SelectablesIndexResponseDefaultTax {
  public static final String SERIALIZED_NAME_TAX_RATE5 = "tax_rate_5";
  @SerializedName(SERIALIZED_NAME_TAX_RATE5)
  private SelectablesIndexResponseDefaultTaxTaxRate5 taxRate5;

  public static final String SERIALIZED_NAME_TAX_RATE8 = "tax_rate_8";
  @SerializedName(SERIALIZED_NAME_TAX_RATE8)
  private SelectablesIndexResponseDefaultTaxTaxRate8 taxRate8;

  public SelectablesIndexResponseDefaultTax() { 
  }

  public SelectablesIndexResponseDefaultTax taxRate5(SelectablesIndexResponseDefaultTaxTaxRate5 taxRate5) {
    
    this.taxRate5 = taxRate5;
    return this;
  }

   /**
   * Get taxRate5
   * @return taxRate5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SelectablesIndexResponseDefaultTaxTaxRate5 getTaxRate5() {
    return taxRate5;
  }


  public void setTaxRate5(SelectablesIndexResponseDefaultTaxTaxRate5 taxRate5) {
    this.taxRate5 = taxRate5;
  }


  public SelectablesIndexResponseDefaultTax taxRate8(SelectablesIndexResponseDefaultTaxTaxRate8 taxRate8) {
    
    this.taxRate8 = taxRate8;
    return this;
  }

   /**
   * Get taxRate8
   * @return taxRate8
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SelectablesIndexResponseDefaultTaxTaxRate8 getTaxRate8() {
    return taxRate8;
  }


  public void setTaxRate8(SelectablesIndexResponseDefaultTaxTaxRate8 taxRate8) {
    this.taxRate8 = taxRate8;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectablesIndexResponseDefaultTax selectablesIndexResponseDefaultTax = (SelectablesIndexResponseDefaultTax) o;
    return Objects.equals(this.taxRate5, selectablesIndexResponseDefaultTax.taxRate5) &&
        Objects.equals(this.taxRate8, selectablesIndexResponseDefaultTax.taxRate8);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taxRate5, taxRate8);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectablesIndexResponseDefaultTax {\n");
    sb.append("    taxRate5: ").append(toIndentedString(taxRate5)).append("\n");
    sb.append("    taxRate8: ").append(toIndentedString(taxRate8)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

