/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.JournalsResponseJournalsUpToDateReasons;
import jp.co.freee.accounting.models.TrialPlThreeYearsResponseTrialPlThreeYears;

/**
 * TrialPlThreeYearsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TrialPlThreeYearsResponse {
  public static final String SERIALIZED_NAME_TRIAL_PL_THREE_YEARS = "trial_pl_three_years";
  @SerializedName(SERIALIZED_NAME_TRIAL_PL_THREE_YEARS)
  private TrialPlThreeYearsResponseTrialPlThreeYears trialPlThreeYears;

  public static final String SERIALIZED_NAME_UP_TO_DATE = "up_to_date";
  @SerializedName(SERIALIZED_NAME_UP_TO_DATE)
  private Boolean upToDate;

  public static final String SERIALIZED_NAME_UP_TO_DATE_REASONS = "up_to_date_reasons";
  @SerializedName(SERIALIZED_NAME_UP_TO_DATE_REASONS)
  private List<JournalsResponseJournalsUpToDateReasons> upToDateReasons = null;

  public TrialPlThreeYearsResponse() { 
  }

  public TrialPlThreeYearsResponse trialPlThreeYears(TrialPlThreeYearsResponseTrialPlThreeYears trialPlThreeYears) {
    
    this.trialPlThreeYears = trialPlThreeYears;
    return this;
  }

   /**
   * Get trialPlThreeYears
   * @return trialPlThreeYears
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public TrialPlThreeYearsResponseTrialPlThreeYears getTrialPlThreeYears() {
    return trialPlThreeYears;
  }


  public void setTrialPlThreeYears(TrialPlThreeYearsResponseTrialPlThreeYears trialPlThreeYears) {
    this.trialPlThreeYears = trialPlThreeYears;
  }


  public TrialPlThreeYearsResponse upToDate(Boolean upToDate) {
    
    this.upToDate = upToDate;
    return this;
  }

   /**
   * 集計結果が最新かどうか
   * @return upToDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "true", required = true, value = "集計結果が最新かどうか")

  public Boolean getUpToDate() {
    return upToDate;
  }


  public void setUpToDate(Boolean upToDate) {
    this.upToDate = upToDate;
  }


  public TrialPlThreeYearsResponse upToDateReasons(List<JournalsResponseJournalsUpToDateReasons> upToDateReasons) {
    
    this.upToDateReasons = upToDateReasons;
    return this;
  }

  public TrialPlThreeYearsResponse addUpToDateReasonsItem(JournalsResponseJournalsUpToDateReasons upToDateReasonsItem) {
    if (this.upToDateReasons == null) {
      this.upToDateReasons = new ArrayList<>();
    }
    this.upToDateReasons.add(upToDateReasonsItem);
    return this;
  }

   /**
   * 集計が最新でない場合の要因情報
   * @return upToDateReasons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "集計が最新でない場合の要因情報")

  public List<JournalsResponseJournalsUpToDateReasons> getUpToDateReasons() {
    return upToDateReasons;
  }


  public void setUpToDateReasons(List<JournalsResponseJournalsUpToDateReasons> upToDateReasons) {
    this.upToDateReasons = upToDateReasons;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrialPlThreeYearsResponse trialPlThreeYearsResponse = (TrialPlThreeYearsResponse) o;
    return Objects.equals(this.trialPlThreeYears, trialPlThreeYearsResponse.trialPlThreeYears) &&
        Objects.equals(this.upToDate, trialPlThreeYearsResponse.upToDate) &&
        Objects.equals(this.upToDateReasons, trialPlThreeYearsResponse.upToDateReasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trialPlThreeYears, upToDate, upToDateReasons);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrialPlThreeYearsResponse {\n");
    sb.append("    trialPlThreeYears: ").append(toIndentedString(trialPlThreeYears)).append("\n");
    sb.append("    upToDate: ").append(toIndentedString(upToDate)).append("\n");
    sb.append("    upToDateReasons: ").append(toIndentedString(upToDateReasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

