/*
 * freee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.freee.accounting.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.freee.accounting.models.JournalsResponseJournalsUpToDateReasons;
import jp.co.freee.accounting.models.TrialPlTwoYearsResponseTrialPlTwoYears;

/**
 * TrialPlTwoYearsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TrialPlTwoYearsResponse {
  public static final String SERIALIZED_NAME_TRIAL_PL_TWO_YEARS = "trial_pl_two_years";
  @SerializedName(SERIALIZED_NAME_TRIAL_PL_TWO_YEARS)
  private TrialPlTwoYearsResponseTrialPlTwoYears trialPlTwoYears;

  public static final String SERIALIZED_NAME_UP_TO_DATE = "up_to_date";
  @SerializedName(SERIALIZED_NAME_UP_TO_DATE)
  private Boolean upToDate;

  public static final String SERIALIZED_NAME_UP_TO_DATE_REASONS = "up_to_date_reasons";
  @SerializedName(SERIALIZED_NAME_UP_TO_DATE_REASONS)
  private List<JournalsResponseJournalsUpToDateReasons> upToDateReasons = null;

  public TrialPlTwoYearsResponse() { 
  }

  public TrialPlTwoYearsResponse trialPlTwoYears(TrialPlTwoYearsResponseTrialPlTwoYears trialPlTwoYears) {
    
    this.trialPlTwoYears = trialPlTwoYears;
    return this;
  }

   /**
   * Get trialPlTwoYears
   * @return trialPlTwoYears
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public TrialPlTwoYearsResponseTrialPlTwoYears getTrialPlTwoYears() {
    return trialPlTwoYears;
  }


  public void setTrialPlTwoYears(TrialPlTwoYearsResponseTrialPlTwoYears trialPlTwoYears) {
    this.trialPlTwoYears = trialPlTwoYears;
  }


  public TrialPlTwoYearsResponse upToDate(Boolean upToDate) {
    
    this.upToDate = upToDate;
    return this;
  }

   /**
   * 集計結果が最新かどうか
   * @return upToDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "true", required = true, value = "集計結果が最新かどうか")

  public Boolean getUpToDate() {
    return upToDate;
  }


  public void setUpToDate(Boolean upToDate) {
    this.upToDate = upToDate;
  }


  public TrialPlTwoYearsResponse upToDateReasons(List<JournalsResponseJournalsUpToDateReasons> upToDateReasons) {
    
    this.upToDateReasons = upToDateReasons;
    return this;
  }

  public TrialPlTwoYearsResponse addUpToDateReasonsItem(JournalsResponseJournalsUpToDateReasons upToDateReasonsItem) {
    if (this.upToDateReasons == null) {
      this.upToDateReasons = new ArrayList<>();
    }
    this.upToDateReasons.add(upToDateReasonsItem);
    return this;
  }

   /**
   * 集計が最新でない場合の要因情報
   * @return upToDateReasons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "集計が最新でない場合の要因情報")

  public List<JournalsResponseJournalsUpToDateReasons> getUpToDateReasons() {
    return upToDateReasons;
  }


  public void setUpToDateReasons(List<JournalsResponseJournalsUpToDateReasons> upToDateReasons) {
    this.upToDateReasons = upToDateReasons;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrialPlTwoYearsResponse trialPlTwoYearsResponse = (TrialPlTwoYearsResponse) o;
    return Objects.equals(this.trialPlTwoYears, trialPlTwoYearsResponse.trialPlTwoYears) &&
        Objects.equals(this.upToDate, trialPlTwoYearsResponse.upToDate) &&
        Objects.equals(this.upToDateReasons, trialPlTwoYearsResponse.upToDateReasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trialPlTwoYears, upToDate, upToDateReasons);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrialPlTwoYearsResponse {\n");
    sb.append("    trialPlTwoYears: ").append(toIndentedString(trialPlTwoYears)).append("\n");
    sb.append("    upToDate: ").append(toIndentedString(upToDate)).append("\n");
    sb.append("    upToDateReasons: ").append(toIndentedString(upToDateReasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

